releases:
  - name: promtail
    version: 0.0.1

addons:
  - name: promtail
    jobs:
      - name: promtail
        release: promtail
        consumes:
          loki: {from: loki, deployment: loki}
    include:
      stemcell:
        - os: ubuntu-trusty
        - os: ubuntu-xenial
    properties: {}
