server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /var/vcap/store/promtail/positions.yaml

client:
  url: http://<%= link('loki').instances.first.address %>:3100/api/prom/push

scrape_configs:
- job_name: system
  entry_parser: raw
  static_configs:
  - targets:
      - localhost
    labels:
      job: varlogs
      __path__: /var/log/*log
- job_name: bosh
  entry_parser: raw
  file_sd_configs:
  - files:
    - "/var/vcap/jobs/promtail/config/bosh/*.yaml"
    refresh_interval: 10m
